#!/bin/bash
#
# This is a positional arguments-only example of Argbash potential
#
# ARG_HELP([The general script's help msg])
# ARG_POSITIONAL_SINGLE([tag-version],[Jito Solana version])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.9.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info
# Generated online by https://argbash.io/generate


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}

begins_with_short_option()
{
	local first_option all_short_options='h'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
_arg_tag_version="v4.1.0-beta.3-jito"
# THE DEFAULTS INITIALIZATION - OPTIONALS


print_help()
{
	printf '%s\n' "The general script's help msg"
	printf 'Usage: %s [-h|--help] <tag-version>\n' "$0"
	printf '\t%s\n' "<tag-version>: Jito Solana version"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	_positionals_count=0
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="'tag-version'"
	test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names="_arg_tag_version "

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

echo Check if required packages are installed.

packages=("libssl-dev" "libudev-dev" "pkg-config" "zlib1g-dev" "llvm" "clang" "cmake" "make" "libprotobuf-dev" "protobuf-compiler")
missing_packages=()

for package in "${packages[@]}"
do
    if dpkg -s "$package" >/dev/null 2>&1; then
        echo "$package is installed."
    else
        missing_packages+=($package)
    fi
done

# shellcheck disable=SC2128
[ "${#missing_packages[@]}" -ne 0 ] && {
    echo ERROR: following packages are missing "${missing_packages[@]}";
    echo hint: sudo apt install -y "${missing_packages[@]}"
    exit 1;
  }

if ! command -v cargo &> /dev/null
then
  curl https://sh.rustup.rs -sSf | sh
fi

source "$HOME/.cargo/env"

rustup component add rustfmt

rustup update

git clone https://github.com/jito-foundation/jito-solana.git --recurse-submodules

TAG=$_arg_tag_version

cd jito-solana || exit

git checkout tags/"$TAG"

git submodule update --init --recursive

CI_COMMIT=$(git rev-parse HEAD) scripts/cargo-install-all.sh --validator-only ~/.local/share/solana/install/releases/"$TAG"

rm -rf "$HOME"/.local/share/solana/install/active_release

ln -sf /home/solana/.local/share/solana/install/releases/"$TAG" "$HOME"/.local/share/solana/install/active_release

# Make the jito release CLI-complete: --validator-only does not build the
# solana CLI / solana-keygen, which the repo's scripts and monitoring need.
# Copy them from a vanilla release (node-base source build or manual tarball
# install) — no-clobber, so jito-built binaries always win. Prefer the exact
# matching version (tag minus v/-jito); otherwise fall back to the newest
# vanilla release present.
VANILLA_VERSION="${TAG#v}"
VANILLA_VERSION="${VANILLA_VERSION%-jito}"
RELEASES_DIR="$HOME/.local/share/solana/install/releases"
EXACT_BIN="$RELEASES_DIR/${VANILLA_VERSION}/solana-release/bin"
JITO_BIN="$RELEASES_DIR/${TAG}/bin"

VANILLA_BIN=""
if [ -x "$EXACT_BIN/solana" ]; then
  VANILLA_BIN="$EXACT_BIN"
else
  while IFS= read -r candidate; do
    if [ -x "$candidate/solana" ]; then
      VANILLA_BIN="$candidate"
      break
    fi
  done < <(find "$RELEASES_DIR" -maxdepth 3 -path '*/solana-release/bin' -type d -printf '%T@ %p\n' 2>/dev/null | sort -rn | cut -d' ' -f2-)
fi

if [ -n "$VANILLA_BIN" ]; then
  if [ "$VANILLA_BIN" != "$EXACT_BIN" ]; then
    echo "NOTE: no vanilla release ${VANILLA_VERSION} found; copying CLI tools from ${VANILLA_BIN} (CLI version differs from the validator — run the playbook to build matching CLI tools)"
  fi
  find "$VANILLA_BIN" -maxdepth 1 -type f -exec cp -n {} "$JITO_BIN"/ \;
elif [ ! -x "$JITO_BIN/solana" ]; then
  echo "WARNING: no vanilla release with CLI tools found under $RELEASES_DIR."
  echo "         solana / solana-keygen will be missing from active_release."
  echo "         Run the playbook (node-base builds the CLI) and re-run this script."
fi

rm -rf "$HOME"/jito-solana