- name: Create mount directories
  file:
    path: "{{ item.mount_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items: "{{ disk_management.disks }}"
  when: disk_management.mount

- name: Format disk
  community.general.filesystem:
    fstype: xfs
    dev: "{{ item.dev }}"
  with_items: "{{ disk_management.disks }}"
  when: disk_management.mount

- name: Mount disks
  mount:
    path: "{{ item.mount_dir }}"
    src: "{{ item.dev }}"
    fstype: "{{ item.fs_type }}"
    opts: "{{ item.options }}"
    state: mounted
  with_items: "{{ disk_management.disks }}"
  when: disk_management.mount

- name: Create sub directories
  file:
    path: "{{ item.mount_dir }}/{{ item.subdir }}"
    state: directory
    owner: "{{ solana_user }}"
    group: "{{ solana_user }}"
    mode: '0755'
  with_items: "{{ disk_management.disks }}"
  when: disk_management.config