# tasks/ramdisk_management.yaml
- name: Ensure ramdisk directories exist
  file:
    path: "{{ item.mount_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items: "{{ ramdisk_management.ramdisks }}"
  when: ramdisk_management.mount

- name: Mount ramdisks
  mount:
    path: "{{ item.mount_dir }}"
    src: "tmpfs"
    fstype: "tmpfs"
    opts: "{{ item.options }}"
    state: mounted
  with_items: "{{ ramdisk_management.ramdisks }}"
  when: ramdisk_management.mount

- name: Create sub directories
  file:
    path: "{{ item.mount_dir }}/{{ item.subdir }}"
    state: directory
    owner: "{{ solana_user }}"
    group: "{{ solana_user }}"
    mode: '0755'
  with_items: "{{ ramdisk_management.ramdisks }}"
  when: ramdisk_management.config